user  nginx;
worker_processes  auto;
pid   /var/run/nginx.pid;

server_tokens off;

events {
    worker_connections  1024;
    multi_accept        on;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format main_json escape=json
        '{'
          '"time":"$time_iso8601",'
          '"remote_addr":"$remote_addr",'
          '"method":"$request_method",'
          '"uri":"$uri",'
          '"status":$status,'
          '"request_time":$request_time'
        '}';

    access_log /dev/stdout main_json;
    error_log  /dev/stderr warn;

    sendfile           on;
    tcp_nopush         on;
    keepalive_timeout  65;
    gzip               on;
    gzip_types         application/json text/plain;

    client_max_body_size    11m;
    client_body_timeout     15s;
    client_header_timeout   15s;
    send_timeout            15s;

    limit_req_zone  $binary_remote_addr  zone=global:10m  rate=20r/s;
    limit_req_zone  $binary_remote_addr  zone=outfits:1m  rate=2r/s;
    limit_req_status 429;

    include /etc/nginx/conf.d/*.conf;
}
